# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chewc',
                'doc_host': 'https://cjGO.github.io',
                'git_url': 'https://github.com/cjGO/chewc',
                'lib_path': 'chewc'},
  'syms': { 'chewc.core': { 'chewc.core.Population': ('population.html#population', 'chewc/core.py'),
                            'chewc.core.Population.__post_init__': ('population.html#population.__post_init__', 'chewc/core.py'),
                            'chewc.core.Population.__repr__': ('population.html#population.__repr__', 'chewc/core.py'),
                            'chewc.core.Population.gv': ('population.html#population.gv', 'chewc/core.py'),
                            'chewc.core.Population.nChr': ('population.html#population.nchr', 'chewc/core.py'),
                            'chewc.core.Population.nInd': ('population.html#population.nind', 'chewc/core.py'),
                            'chewc.core.Population.nLoci': ('population.html#population.nloci', 'chewc/core.py'),
                            'chewc.core.Population.nTraits': ('population.html#population.ntraits', 'chewc/core.py'),
                            'chewc.core._pad_and_stack_arrays': ('population.html#_pad_and_stack_arrays', 'chewc/core.py'),
                            'chewc.core.quick_haplo': ('population.html#quick_haplo', 'chewc/core.py')}}}
