# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chewc',
                'doc_host': 'https://cjGO.github.io',
                'git_url': 'https://github.com/cjGO/chewc',
                'lib_path': 'chewc'},
  'syms': { 'chewc.api': {},
            'chewc.pheno': { 'chewc.pheno.calculate_phenotypes': ('phenotype.html#calculate_phenotypes', 'chewc/pheno.py'),
                             'chewc.pheno.compute_dosage': ('phenotype.html#compute_dosage', 'chewc/pheno.py')},
            'chewc.structs': { 'chewc.structs.BreedingState': ('structs.html#breedingstate', 'chewc/structs.py'),
                               'chewc.structs.GeneticMap': ('structs.html#geneticmap', 'chewc/structs.py'),
                               'chewc.structs.Population': ('structs.html#population', 'chewc/structs.py'),
                               'chewc.structs.Trait': ('structs.html#trait', 'chewc/structs.py'),
                               'chewc.structs.add_trait': ('structs.html#add_trait', 'chewc/structs.py'),
                               'chewc.structs.compute_dosage': ('structs.html#compute_dosage', 'chewc/structs.py'),
                               'chewc.structs.quick_haplo': ('structs.html#quick_haplo', 'chewc/structs.py')},
            'chewc.workflow': {}}}
