# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chewc',
                'doc_host': 'https://cjGO.github.io',
                'git_url': 'https://github.com/cjGO/chewc',
                'lib_path': 'chewc'},
  'syms': {'chewc.core': {'chewc.core.quickHaplo': ('genome_simulation copy.html#quickhaplo', 'chewc/core.py')}}}
