"""Reproduction of the quickhaplo functionality"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_genome_simulation copy.ipynb.

# %% auto 0
__all__ = ['quickHaplo']

# %% ../nbs/02_genome_simulation copy.ipynb 3
def quickHaplo():
    """
    founderPop = quickHaplo(nInd=10, nChr=1, segSites=100)
    """
    pass
