# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_popgen.ipynb.

# %% auto 0
__all__ = ['create_founders']

# %% ../nbs/02_popgen.ipynb 1
import jax
import jax.numpy as jnp
from .config import StaticConfig, Population

# %% ../nbs/02_popgen.ipynb 2
def create_founders(key: jax.random.PRNGKey, s_config: StaticConfig, n_founders: int) -> Population:
    geno = jax.random.randint(
        key,
        (n_founders, s_config.n_chr, s_config.ploidy, s_config.n_loci_per_chr),
        0,
        2,
        dtype=jnp.int8,
    )
    ids = jnp.arange(n_founders, dtype=jnp.int32)[:, None]
    parent_ids = jnp.full((n_founders, 2), -1, dtype=jnp.int32)
    birth_gen = jnp.zeros((n_founders, 1), dtype=jnp.int32)
    return Population(geno=geno, meta=jnp.hstack([ids, parent_ids, birth_gen]))
