# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_select.ipynb.

# %% auto 0
__all__ = ['select_top_k']

# %% ../nbs/05_select.ipynb 1
import jax
from jax import lax
import jax.numpy as jnp
from typing import Tuple
from .meiosis import create_gamete
from .structs import GeneticMap, Population
from jax.tree_util import tree_map

from functools import partial
@partial(jax.jit, static_argnames=("k",))
def select_top_k(population: Population, values: jnp.ndarray, k: int) -> Population:
    """Select top-k individuals by `values` (1-D)."""
    vals = jnp.ravel(values).astype(jnp.float32)  # (n_ind,)
    _, top_idx = lax.top_k(vals, k)               # (k,)
    return tree_map(lambda x: x[top_idx], population)


