# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_state.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_state.ipynb 2
import jax
import jax.numpy as jnp
from fastcore.test import test_eq, test_ne

from flax.struct import dataclass as flax_dataclass
from .config import SimConfig
from .structs import Population, SimParam

import warnings

