# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_workflow.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_workflow.ipynb 1
import jax
import jax.numpy as jnp

# Assuming 'chewc' is installed or in the python path
from .structs import quick_haplo, add_trait

